import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type LanguageCode = 'en' | 'es' | 'ja' | 'ko' | 'zh' | 'fr' | 'de' | 'pt' | 'ru' | 'ar';

export interface Language {
  code: LanguageCode;
  name: string;
  abbr: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', abbr: 'ENG', flag: '🇺🇸' },
  { code: 'es', name: 'Español', abbr: 'SPA', flag: '🇪🇸' },
  { code: 'ja', name: '日本語', abbr: 'JAP', flag: '🇯🇵' },
  { code: 'ko', name: '한국어', abbr: 'KOR', flag: '🇰🇷' },
  { code: 'zh', name: '中文', abbr: 'CHN', flag: '🇨🇳' },
  { code: 'fr', name: 'Français', abbr: 'FRA', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', abbr: 'DEU', flag: '🇩🇪' },
  { code: 'pt', name: 'Português', abbr: 'POR', flag: '🇧🇷' },
  { code: 'ru', name: 'Русский', abbr: 'RUS', flag: '🇷🇺' },
  { code: 'ar', name: 'العربية', abbr: 'ARA', flag: '🇸🇦' },
];

type TranslationKey = 
  | 'home' | 'about' | 'giphy' | 'memes' | 'xpCard' | 'pfp' | 'buyNow'
  | 'darkMode' | 'language' | 'signIn' | 'signUp' | 'signInSignUp' | 'signOut'
  | 'profile' | 'search' | 'searchProfiles' | 'searchPlaceholder' | 'noResults' | 'searching'
  | 'preview' | 'weekly' | 'allTime' | 'username' | 'xpAmount' | 'uploadPhoto' | 'downloadCard'
  | 'yourPudgy' | 'yourLil' | 'uploadPudgy' | 'uploadLil' | 'detectedTraits' | 'downloadPFP'
  | 'comingSoon' | 'big' | 'lil';

type Translations = Record<LanguageCode, Record<TranslationKey, string>>;

const translations: Translations = {
  en: {
    home: 'Home',
    about: 'About',
    giphy: 'Giphy',
    memes: 'Memes',
    xpCard: 'XP Card',
    pfp: 'PFP',
    buyNow: 'Buy Now',
    darkMode: 'Dark Mode',
    language: 'Language',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signInSignUp: 'Sign In / Sign Up',
    signOut: 'Sign Out',
    profile: 'Profile',
    search: 'Search',
    searchProfiles: 'Search Profiles',
    searchPlaceholder: 'Search by username or display name...',
    noResults: 'No profiles found',
    searching: 'Searching...',
    preview: 'Preview',
    weekly: 'Weekly',
    allTime: 'All-Time',
    username: 'Username',
    xpAmount: 'XP Amount',
    uploadPhoto: 'Upload Photo',
    downloadCard: 'Download XP Card',
    yourPudgy: 'Your Pudgy',
    yourLil: 'Your Lil',
    uploadPudgy: 'Upload your Pudgy Penguin NFT',
    uploadLil: 'Upload your Lil Pudgy NFT',
    detectedTraits: 'Detected Traits',
    downloadPFP: 'Download PFP',
    comingSoon: 'Coming Soon',
    big: 'Big',
    lil: 'Lil',
  },
  es: {
    home: 'Inicio',
    about: 'Acerca de',
    giphy: 'Giphy',
    memes: 'Memes',
    xpCard: 'Tarjeta XP',
    pfp: 'PFP',
    buyNow: 'Comprar Ahora',
    darkMode: 'Modo Oscuro',
    language: 'Idioma',
    signIn: 'Iniciar Sesión',
    signUp: 'Registrarse',
    signInSignUp: 'Iniciar / Registrarse',
    signOut: 'Cerrar Sesión',
    profile: 'Perfil',
    search: 'Buscar',
    searchProfiles: 'Buscar Perfiles',
    searchPlaceholder: 'Buscar por nombre de usuario...',
    noResults: 'No se encontraron perfiles',
    searching: 'Buscando...',
    preview: 'Vista Previa',
    weekly: 'Semanal',
    allTime: 'Todo el Tiempo',
    username: 'Nombre de Usuario',
    xpAmount: 'Cantidad de XP',
    uploadPhoto: 'Subir Foto',
    downloadCard: 'Descargar Tarjeta XP',
    yourPudgy: 'Tu Pudgy',
    yourLil: 'Tu Lil',
    uploadPudgy: 'Sube tu NFT de Pudgy Penguin',
    uploadLil: 'Sube tu NFT de Lil Pudgy',
    detectedTraits: 'Rasgos Detectados',
    downloadPFP: 'Descargar PFP',
    comingSoon: 'Próximamente',
    big: 'Grande',
    lil: 'Pequeño',
  },
  ja: {
    home: 'ホーム',
    about: '概要',
    giphy: 'Giphy',
    memes: 'ミーム',
    xpCard: 'XPカード',
    pfp: 'PFP',
    buyNow: '今すぐ購入',
    darkMode: 'ダークモード',
    language: '言語',
    signIn: 'サインイン',
    signUp: 'サインアップ',
    signInSignUp: 'サインイン / サインアップ',
    signOut: 'サインアウト',
    profile: 'プロフィール',
    search: '検索',
    searchProfiles: 'プロフィールを検索',
    searchPlaceholder: 'ユーザー名で検索...',
    noResults: 'プロフィールが見つかりません',
    searching: '検索中...',
    preview: 'プレビュー',
    weekly: '週間',
    allTime: '全期間',
    username: 'ユーザー名',
    xpAmount: 'XP量',
    uploadPhoto: '写真をアップロード',
    downloadCard: 'XPカードをダウンロード',
    yourPudgy: 'あなたのPudgy',
    yourLil: 'あなたのLil',
    uploadPudgy: 'Pudgy Penguin NFTをアップロード',
    uploadLil: 'Lil Pudgy NFTをアップロード',
    detectedTraits: '検出された特性',
    downloadPFP: 'PFPをダウンロード',
    comingSoon: '近日公開',
    big: 'ビッグ',
    lil: 'リル',
  },
  ko: {
    home: '홈',
    about: '소개',
    giphy: 'Giphy',
    memes: '밈',
    xpCard: 'XP 카드',
    pfp: 'PFP',
    buyNow: '지금 구매',
    darkMode: '다크 모드',
    language: '언어',
    signIn: '로그인',
    signUp: '가입',
    signInSignUp: '로그인 / 가입',
    signOut: '로그아웃',
    profile: '프로필',
    search: '검색',
    searchProfiles: '프로필 검색',
    searchPlaceholder: '사용자 이름으로 검색...',
    noResults: '프로필을 찾을 수 없습니다',
    searching: '검색 중...',
    preview: '미리보기',
    weekly: '주간',
    allTime: '전체 기간',
    username: '사용자 이름',
    xpAmount: 'XP 양',
    uploadPhoto: '사진 업로드',
    downloadCard: 'XP 카드 다운로드',
    yourPudgy: '당신의 Pudgy',
    yourLil: '당신의 Lil',
    uploadPudgy: 'Pudgy Penguin NFT 업로드',
    uploadLil: 'Lil Pudgy NFT 업로드',
    detectedTraits: '감지된 특성',
    downloadPFP: 'PFP 다운로드',
    comingSoon: '곧 출시',
    big: '큰',
    lil: '작은',
  },
  zh: {
    home: '首页',
    about: '关于',
    giphy: 'Giphy',
    memes: '表情包',
    xpCard: 'XP卡片',
    pfp: 'PFP',
    buyNow: '立即购买',
    darkMode: '深色模式',
    language: '语言',
    signIn: '登录',
    signUp: '注册',
    signInSignUp: '登录 / 注册',
    signOut: '退出',
    profile: '个人资料',
    search: '搜索',
    searchProfiles: '搜索用户',
    searchPlaceholder: '按用户名搜索...',
    noResults: '未找到用户',
    searching: '搜索中...',
    preview: '预览',
    weekly: '每周',
    allTime: '全部时间',
    username: '用户名',
    xpAmount: 'XP数量',
    uploadPhoto: '上传照片',
    downloadCard: '下载XP卡片',
    yourPudgy: '你的Pudgy',
    yourLil: '你的Lil',
    uploadPudgy: '上传你的Pudgy Penguin NFT',
    uploadLil: '上传你的Lil Pudgy NFT',
    detectedTraits: '检测到的特征',
    downloadPFP: '下载PFP',
    comingSoon: '即将推出',
    big: '大',
    lil: '小',
  },
  fr: {
    home: 'Accueil',
    about: 'À propos',
    giphy: 'Giphy',
    memes: 'Mèmes',
    xpCard: 'Carte XP',
    pfp: 'PFP',
    buyNow: 'Acheter',
    darkMode: 'Mode Sombre',
    language: 'Langue',
    signIn: 'Connexion',
    signUp: 'Inscription',
    signInSignUp: 'Connexion / Inscription',
    signOut: 'Déconnexion',
    profile: 'Profil',
    search: 'Rechercher',
    searchProfiles: 'Rechercher des Profils',
    searchPlaceholder: 'Rechercher par nom...',
    noResults: 'Aucun profil trouvé',
    searching: 'Recherche...',
    preview: 'Aperçu',
    weekly: 'Hebdomadaire',
    allTime: 'Tout le Temps',
    username: "Nom d'utilisateur",
    xpAmount: 'Quantité XP',
    uploadPhoto: 'Télécharger Photo',
    downloadCard: 'Télécharger Carte XP',
    yourPudgy: 'Ton Pudgy',
    yourLil: 'Ton Lil',
    uploadPudgy: 'Télécharge ton NFT Pudgy Penguin',
    uploadLil: 'Télécharge ton NFT Lil Pudgy',
    detectedTraits: 'Traits Détectés',
    downloadPFP: 'Télécharger PFP',
    comingSoon: 'Bientôt Disponible',
    big: 'Grand',
    lil: 'Petit',
  },
  de: {
    home: 'Startseite',
    about: 'Über uns',
    giphy: 'Giphy',
    memes: 'Memes',
    xpCard: 'XP-Karte',
    pfp: 'PFP',
    buyNow: 'Jetzt Kaufen',
    darkMode: 'Dunkelmodus',
    language: 'Sprache',
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    signInSignUp: 'Anmelden / Registrieren',
    signOut: 'Abmelden',
    profile: 'Profil',
    search: 'Suchen',
    searchProfiles: 'Profile Suchen',
    searchPlaceholder: 'Nach Benutzername suchen...',
    noResults: 'Keine Profile gefunden',
    searching: 'Suche...',
    preview: 'Vorschau',
    weekly: 'Wöchentlich',
    allTime: 'Gesamtzeit',
    username: 'Benutzername',
    xpAmount: 'XP-Menge',
    uploadPhoto: 'Foto Hochladen',
    downloadCard: 'XP-Karte Herunterladen',
    yourPudgy: 'Dein Pudgy',
    yourLil: 'Dein Lil',
    uploadPudgy: 'Lade dein Pudgy Penguin NFT hoch',
    uploadLil: 'Lade dein Lil Pudgy NFT hoch',
    detectedTraits: 'Erkannte Merkmale',
    downloadPFP: 'PFP Herunterladen',
    comingSoon: 'Demnächst',
    big: 'Groß',
    lil: 'Klein',
  },
  pt: {
    home: 'Início',
    about: 'Sobre',
    giphy: 'Giphy',
    memes: 'Memes',
    xpCard: 'Cartão XP',
    pfp: 'PFP',
    buyNow: 'Comprar Agora',
    darkMode: 'Modo Escuro',
    language: 'Idioma',
    signIn: 'Entrar',
    signUp: 'Cadastrar',
    signInSignUp: 'Entrar / Cadastrar',
    signOut: 'Sair',
    profile: 'Perfil',
    search: 'Buscar',
    searchProfiles: 'Buscar Perfis',
    searchPlaceholder: 'Buscar por nome de usuário...',
    noResults: 'Nenhum perfil encontrado',
    searching: 'Buscando...',
    preview: 'Prévia',
    weekly: 'Semanal',
    allTime: 'Todo o Tempo',
    username: 'Nome de Usuário',
    xpAmount: 'Quantidade de XP',
    uploadPhoto: 'Enviar Foto',
    downloadCard: 'Baixar Cartão XP',
    yourPudgy: 'Seu Pudgy',
    yourLil: 'Seu Lil',
    uploadPudgy: 'Envie seu NFT Pudgy Penguin',
    uploadLil: 'Envie seu NFT Lil Pudgy',
    detectedTraits: 'Características Detectadas',
    downloadPFP: 'Baixar PFP',
    comingSoon: 'Em Breve',
    big: 'Grande',
    lil: 'Pequeno',
  },
  ru: {
    home: 'Главная',
    about: 'О нас',
    giphy: 'Giphy',
    memes: 'Мемы',
    xpCard: 'XP Карта',
    pfp: 'PFP',
    buyNow: 'Купить',
    darkMode: 'Тёмный Режим',
    language: 'Язык',
    signIn: 'Войти',
    signUp: 'Регистрация',
    signInSignUp: 'Войти / Регистрация',
    signOut: 'Выйти',
    profile: 'Профиль',
    search: 'Поиск',
    searchProfiles: 'Поиск Профилей',
    searchPlaceholder: 'Поиск по имени...',
    noResults: 'Профили не найдены',
    searching: 'Поиск...',
    preview: 'Предпросмотр',
    weekly: 'Еженедельно',
    allTime: 'Всё Время',
    username: 'Имя пользователя',
    xpAmount: 'Количество XP',
    uploadPhoto: 'Загрузить Фото',
    downloadCard: 'Скачать XP Карту',
    yourPudgy: 'Ваш Pudgy',
    yourLil: 'Ваш Lil',
    uploadPudgy: 'Загрузите ваш Pudgy Penguin NFT',
    uploadLil: 'Загрузите ваш Lil Pudgy NFT',
    detectedTraits: 'Обнаруженные Черты',
    downloadPFP: 'Скачать PFP',
    comingSoon: 'Скоро',
    big: 'Большой',
    lil: 'Маленький',
  },
  ar: {
    home: 'الرئيسية',
    about: 'حول',
    giphy: 'Giphy',
    memes: 'ميمز',
    xpCard: 'بطاقة XP',
    pfp: 'PFP',
    buyNow: 'اشتري الآن',
    darkMode: 'الوضع الداكن',
    language: 'اللغة',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    signInSignUp: 'دخول / تسجيل',
    signOut: 'تسجيل الخروج',
    profile: 'الملف الشخصي',
    search: 'بحث',
    searchProfiles: 'البحث عن مستخدمين',
    searchPlaceholder: 'البحث باسم المستخدم...',
    noResults: 'لم يتم العثور على مستخدمين',
    searching: 'جاري البحث...',
    preview: 'معاينة',
    weekly: 'أسبوعي',
    allTime: 'كل الأوقات',
    username: 'اسم المستخدم',
    xpAmount: 'كمية XP',
    uploadPhoto: 'رفع صورة',
    downloadCard: 'تحميل بطاقة XP',
    yourPudgy: 'Pudgy الخاص بك',
    yourLil: 'Lil الخاص بك',
    uploadPudgy: 'ارفع NFT الخاص بـ Pudgy Penguin',
    uploadLil: 'ارفع NFT الخاص بـ Lil Pudgy',
    detectedTraits: 'السمات المكتشفة',
    downloadPFP: 'تحميل PFP',
    comingSoon: 'قريباً',
    big: 'كبير',
    lil: 'صغير',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  t: (key: TranslationKey) => string;
  currentLanguage: Language;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('language');
    return (saved as LanguageCode) || 'en';
  });

  const setLanguage = (code: LanguageCode) => {
    setLanguageState(code);
    localStorage.setItem('language', code);
  };

  const t = (key: TranslationKey): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  const currentLanguage = LANGUAGES.find(l => l.code === language) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
