import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type LanguageCode = 'en' | 'es' | 'ja' | 'ko' | 'zh' | 'fr' | 'de' | 'pt' | 'ru' | 'ar';

export interface Language {
  code: LanguageCode;
  name: string;
  abbr: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', abbr: 'ENG', flag: '🇺🇸' },
  { code: 'es', name: 'Español', abbr: 'SPA', flag: '🇪🇸' },
  { code: 'ja', name: '日本語', abbr: 'JAP', flag: '🇯🇵' },
  { code: 'ko', name: '한국어', abbr: 'KOR', flag: '🇰🇷' },
  { code: 'zh', name: '中文', abbr: 'CHN', flag: '🇨🇳' },
  { code: 'fr', name: 'Français', abbr: 'FRA', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', abbr: 'DEU', flag: '🇩🇪' },
  { code: 'pt', name: 'Português', abbr: 'POR', flag: '🇧🇷' },
  { code: 'ru', name: 'Русский', abbr: 'RUS', flag: '🇷🇺' },
  { code: 'ar', name: 'العربية', abbr: 'ARA', flag: '🇸🇦' },
];

type TranslationKey = 
  // Nav
  | 'home' | 'about' | 'giphy' | 'memes' | 'xpCard' | 'pfp' | 'wallpapers' | 'claim' | 'buyNow'
  | 'darkMode' | 'language' | 'signIn' | 'signUp' | 'signInSignUp' | 'signOut'
  | 'profile' | 'search' | 'searchProfiles' | 'searchPlaceholder' | 'noResults' | 'searching'
  // XP Card
  | 'preview' | 'weekly' | 'allTime' | 'username' | 'xpAmount' | 'uploadPhoto' | 'downloadCard'
  | 'customizeYourCard' | 'enterUsername' | 'profilePhoto' | 'uploadProfilePhoto' | 'changePhoto' | 'photoUploaded' | 'remove'
  // PFP
  | 'yourPudgy' | 'yourLil' | 'uploadPudgy' | 'uploadLil' | 'detectedTraits' | 'downloadPFP'
  | 'comingSoon' | 'big' | 'lil' | 'pfpTitle' | 'howItWorks' | 'step1Title' | 'step1Desc'
  | 'step2Title' | 'step2Desc' | 'step3Title' | 'step3Desc'
  | 'yourRetsba' | 'retsbafied' | 'dropPudgyHere' | 'orClickToBrowse' | 'download' | 'tryAgain' | 'confidence'
  // Hero
  | 'heroTagline' | 'heroButton'
  // About
  | 'aboutTitle' | 'aboutSubtitle' | 'aboutDescription'
  // How to Buy
  | 'buyNowTitle' | 'getOnAbstract' | 'getOnAbstractDesc' | 'fundAccount' | 'fundAccountDesc'
  | 'clickTrade' | 'clickTradeDesc' | 'buyRetsba' | 'buyRetsbaDesc'
  // Footer
  | 'footerTagline'
  // Trading Interface
  | 'buyRetsbaTitle' | 'connectWalletToContinue' | 'tokenBalance' | 'retsbaBalance'
  | 'loading' | 'amountToCorrupt' | 'youWillReceive' | 'loadingPriceData'
  | 'submitting' | 'loadingPrice' | 'becomeTheVillain' | 'slippageApplied'
  // Wallet
  | 'connectAGW';

type Translations = Record<LanguageCode, Record<TranslationKey, string>>;

const translations: Translations = {
  en: {
    // Nav
    home: 'Home',
    about: 'About',
    giphy: 'Giphy',
    memes: 'Memes',
    xpCard: 'XP Card',
    pfp: 'PFP',
    wallpapers: 'Wallpapers',
    buyNow: 'Buy Now',
    darkMode: 'Dark Mode',
    language: 'Language',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signInSignUp: 'Sign In / Sign Up',
    signOut: 'Sign Out',
    profile: 'Profile',
    search: 'Search',
    searchProfiles: 'Search Profiles',
    searchPlaceholder: 'Search by username or display name...',
    noResults: 'No profiles found',
    searching: 'Searching...',
    // XP Card
    preview: 'Preview',
    weekly: 'Weekly',
    allTime: 'All-Time',
    username: 'Username',
    xpAmount: 'XP Amount',
    uploadPhoto: 'Upload Photo',
    downloadCard: 'Download XP Card',
    customizeYourCard: 'Customize Your Card',
    enterUsername: 'Enter your username',
    profilePhoto: 'Profile Photo',
    uploadProfilePhoto: 'Upload Profile Photo',
    changePhoto: 'Change Photo',
    photoUploaded: 'Photo uploaded',
    remove: 'Remove',
    // PFP
    yourPudgy: 'Your Pudgy',
    yourLil: 'Your Lil (Beta)',
    uploadPudgy: 'Upload your Pudgy Penguin NFT',
    uploadLil: 'Upload your Lil Pudgy NFT',
    detectedTraits: 'Detected Traits',
    downloadPFP: 'Download PFP',
    comingSoon: 'Coming Soon',
    big: 'Big',
    lil: 'Lil (Beta)',
    pfpTitle: 'Profile Picture Converter',
    howItWorks: 'How It Works',
    step1Title: 'Upload Your Pudgy',
    step1Desc: 'Select your Pudgy Penguin NFT image from your device.',
    step2Title: 'AI Detection',
    step2Desc: 'Our AI analyzes and detects the traits of your Pudgy.',
    step3Title: 'Get Your Retsba',
    step3Desc: 'Download your unique Retsbafied profile picture.',
    yourRetsba: 'Your Retsba',
    retsbafied: 'Retsbafied',
    dropPudgyHere: 'Drop your Pudgy here',
    orClickToBrowse: 'or click to browse',
    download: 'Download',
    tryAgain: 'Try Again',
    confidence: 'confidence',
    // Hero
    heroTagline: 'Evil. On Chain.',
    heroButton: 'BE THE VILLAIN',
    // About
    aboutTitle: 'RETSBA',
    aboutSubtitle: 'The memecoin with a darkside',
    aboutDescription: 'Every great legend in history has had one commonality: there is a hero, and there is a villain. In a world of heroic Pudgy Penguins, Retsba is the villain. Hailing from the depths of Anti-Abstract, his relentless conquest of evil will not end until he gains total dominion over the Abstract blockchain.',
    // How to Buy
    buyNowTitle: 'BUY NOW',
    getOnAbstract: 'Get on Abstract',
    getOnAbstractDesc: 'Go to abs.xyz.',
    fundAccount: 'Fund your account',
    fundAccountDesc: 'Click the "Fund" button and bridge Abstract ETH, or transfer straight from another wallet.',
    clickTrade: 'Click "Trade"',
    clickTradeDesc: 'Navigate to the trading section on Abstract.',
    buyRetsba: 'Buy $RETSBA',
    buyRetsbaDesc: 'Search for and purchase RETSBA tokens.',
    // Footer
    footerTagline: 'Evil. On chain.',
    // Trading Interface
    buyRetsbaTitle: 'Buy RETSBA',
    connectWalletToContinue: 'Please connect your wallet to continue',
    tokenBalance: 'Token Balance',
    retsbaBalance: 'RETSBA Balance',
    loading: 'Loading...',
    amountToCorrupt: 'Amount to corrupt',
    youWillReceive: 'You will receive (estimated)',
    loadingPriceData: 'Loading price data...',
    submitting: 'Submitting...',
    loadingPrice: 'Loading Price...',
    becomeTheVillain: 'Become the Villain',
    slippageApplied: 'slippage applied',
    connectAGW: 'Connect',
  },
  es: {
    home: 'Inicio',
    about: 'Acerca de',
    giphy: 'Giphy',
    memes: 'Memes',
    xpCard: 'Tarjeta XP',
    pfp: 'PFP',
    wallpapers: 'Fondos de Pantalla',
    buyNow: 'Comprar Ahora',
    darkMode: 'Modo Oscuro',
    language: 'Idioma',
    signIn: 'Iniciar Sesión',
    signUp: 'Registrarse',
    signInSignUp: 'Iniciar / Registrarse',
    signOut: 'Cerrar Sesión',
    profile: 'Perfil',
    search: 'Buscar',
    searchProfiles: 'Buscar Perfiles',
    searchPlaceholder: 'Buscar por nombre de usuario...',
    noResults: 'No se encontraron perfiles',
    searching: 'Buscando...',
    preview: 'Vista Previa',
    weekly: 'Semanal',
    allTime: 'Todo el Tiempo',
    username: 'Nombre de Usuario',
    xpAmount: 'Cantidad de XP',
    uploadPhoto: 'Subir Foto',
    downloadCard: 'Descargar Tarjeta XP',
    customizeYourCard: 'Personaliza Tu Tarjeta',
    enterUsername: 'Ingresa tu nombre de usuario',
    profilePhoto: 'Foto de Perfil',
    uploadProfilePhoto: 'Subir Foto de Perfil',
    changePhoto: 'Cambiar Foto',
    photoUploaded: 'Foto subida',
    remove: 'Eliminar',
    yourPudgy: 'Tu Pudgy',
    yourLil: 'Tu Lil (Beta)',
    uploadPudgy: 'Sube tu NFT de Pudgy Penguin',
    uploadLil: 'Sube tu NFT de Lil Pudgy',
    detectedTraits: 'Rasgos Detectados',
    downloadPFP: 'Descargar PFP',
    comingSoon: 'Próximamente',
    big: 'Big',
    lil: 'Lil (Beta)',
    pfpTitle: 'Convertidor de Foto de Perfil',
    howItWorks: 'Cómo Funciona',
    step1Title: 'Sube Tu Pudgy',
    step1Desc: 'Selecciona la imagen de tu NFT Pudgy Penguin.',
    step2Title: 'Detección IA',
    step2Desc: 'Nuestra IA analiza y detecta los rasgos de tu Pudgy.',
    step3Title: 'Obtén Tu Retsba',
    step3Desc: 'Descarga tu foto de perfil Retsbafied única.',
    yourRetsba: 'Tu Retsba',
    retsbafied: 'Retsbafied',
    dropPudgyHere: 'Arrastra tu Pudgy aquí',
    orClickToBrowse: 'o haz clic para buscar',
    download: 'Descargar',
    tryAgain: 'Intentar de Nuevo',
    confidence: 'confianza',
    heroTagline: 'Malvado. En Cadena.',
    heroButton: 'SÉ EL VILLANO',
    aboutTitle: 'RETSBA',
    aboutSubtitle: 'La memecoin con un lado oscuro',
    aboutDescription: 'Toda gran leyenda en la historia ha tenido algo en común: hay un héroe y hay un villano. En un mundo de heroicos Pudgy Penguins, Retsba es el villano. Procedente de las profundidades de Anti-Abstract, su incansable conquista del mal no terminará hasta que obtenga el dominio total sobre la blockchain Abstract.',
    buyNowTitle: 'COMPRAR AHORA',
    getOnAbstract: 'Entra en Abstract',
    getOnAbstractDesc: 'Ve a abs.xyz.',
    fundAccount: 'Fondea tu cuenta',
    fundAccountDesc: 'Haz clic en "Fund" y transfiere Abstract ETH.',
    clickTrade: 'Haz clic en "Trade"',
    clickTradeDesc: 'Navega a la sección de trading en Abstract.',
    buyRetsba: 'Compra $RETSBA',
    buyRetsbaDesc: 'Busca y compra tokens RETSBA.',
    footerTagline: 'Malvado. En cadena.',
    buyRetsbaTitle: 'Comprar RETSBA',
    connectWalletToContinue: 'Por favor conecta tu billetera para continuar',
    tokenBalance: 'Saldo de Token',
    retsbaBalance: 'Saldo de RETSBA',
    loading: 'Cargando...',
    amountToCorrupt: 'Cantidad a corromper',
    youWillReceive: 'Recibirás (estimado)',
    loadingPriceData: 'Cargando datos de precio...',
    submitting: 'Enviando...',
    loadingPrice: 'Cargando Precio...',
    becomeTheVillain: 'Conviértete en el Villano',
    slippageApplied: 'deslizamiento aplicado',
    connectAGW: 'Conectar',
  },
  ja: {
    home: 'ホーム',
    about: '概要',
    giphy: 'Giphy',
    memes: 'ミーム',
    xpCard: 'XPカード',
    pfp: 'PFP',
    wallpapers: '壁紙',
    buyNow: '今すぐ購入',
    darkMode: 'ダークモード',
    language: '言語',
    signIn: 'サインイン',
    signUp: 'サインアップ',
    signInSignUp: 'サインイン / サインアップ',
    signOut: 'サインアウト',
    profile: 'プロフィール',
    search: '検索',
    searchProfiles: 'プロフィールを検索',
    searchPlaceholder: 'ユーザー名で検索...',
    noResults: 'プロフィールが見つかりません',
    searching: '検索中...',
    preview: 'プレビュー',
    weekly: '週間',
    allTime: '全期間',
    username: 'ユーザー名',
    xpAmount: 'XP量',
    uploadPhoto: '写真をアップロード',
    downloadCard: 'XPカードをダウンロード',
    customizeYourCard: 'カードをカスタマイズ',
    enterUsername: 'ユーザー名を入力',
    profilePhoto: 'プロフィール写真',
    uploadProfilePhoto: 'プロフィール写真をアップロード',
    changePhoto: '写真を変更',
    photoUploaded: '写真がアップロードされました',
    remove: '削除',
    yourPudgy: 'あなたのPudgy',
    yourLil: 'あなたのLil (Beta)',
    uploadPudgy: 'Pudgy Penguin NFTをアップロード',
    uploadLil: 'Lil Pudgy NFTをアップロード',
    detectedTraits: '検出された特性',
    downloadPFP: 'PFPをダウンロード',
    comingSoon: '近日公開',
    big: 'Big',
    lil: 'Lil (Beta)',
    pfpTitle: 'プロフィール画像コンバーター',
    howItWorks: '使い方',
    step1Title: 'Pudgyをアップロード',
    step1Desc: 'デバイスからPudgy Penguin NFT画像を選択。',
    step2Title: 'AI検出',
    step2Desc: 'AIがPudgyの特性を分析・検出。',
    step3Title: 'Retsbaを入手',
    step3Desc: 'ユニークなRetsba化プロフィール画像をダウンロード。',
    yourRetsba: 'あなたのRetsba',
    retsbafied: 'Retsbafied',
    dropPudgyHere: 'Pudgyをここにドロップ',
    orClickToBrowse: 'またはクリックして参照',
    download: 'ダウンロード',
    tryAgain: '再試行',
    confidence: '信頼度',
    heroTagline: '悪。オンチェーン。',
    heroButton: '悪役になれ',
    aboutTitle: 'RETSBA',
    aboutSubtitle: 'ダークサイドを持つミームコイン',
    aboutDescription: '歴史上のすべての偉大な伝説には共通点があります：ヒーローとヴィランがいます。英雄的なPudgy Penguinsの世界で、Retsbaはヴィランです。Anti-Abstractの深淵から現れた彼は、Abstractブロックチェーンを完全に支配するまで悪の征服を止めません。',
    buyNowTitle: '今すぐ購入',
    getOnAbstract: 'Abstractに参加',
    getOnAbstractDesc: 'abs.xyzにアクセス。',
    fundAccount: 'アカウントに入金',
    fundAccountDesc: '「Fund」をクリックしてAbstract ETHをブリッジ。',
    clickTrade: '「Trade」をクリック',
    clickTradeDesc: 'Abstractのトレーディングセクションへ移動。',
    buyRetsba: '$RETSBAを購入',
    buyRetsbaDesc: 'RETSBAトークンを検索して購入。',
    footerTagline: '悪。オンチェーン。',
    buyRetsbaTitle: 'RETSBAを購入',
    connectWalletToContinue: 'ウォレットを接続してください',
    tokenBalance: 'トークン残高',
    retsbaBalance: 'RETSBA残高',
    loading: '読み込み中...',
    amountToCorrupt: '堕落させる量',
    youWillReceive: '受け取り予定（推定）',
    loadingPriceData: '価格データを読み込み中...',
    submitting: '送信中...',
    loadingPrice: '価格を読み込み中...',
    becomeTheVillain: '悪役になれ',
    slippageApplied: 'スリッページ適用',
    connectAGW: '接続',
  },
  ko: {
    home: '홈',
    about: '소개',
    giphy: 'Giphy',
    memes: '밈',
    xpCard: 'XP 카드',
    pfp: 'PFP',
    wallpapers: '배경화면',
    buyNow: '지금 구매',
    darkMode: '다크 모드',
    language: '언어',
    signIn: '로그인',
    signUp: '가입',
    signInSignUp: '로그인 / 가입',
    signOut: '로그아웃',
    profile: '프로필',
    search: '검색',
    searchProfiles: '프로필 검색',
    searchPlaceholder: '사용자 이름으로 검색...',
    noResults: '프로필을 찾을 수 없습니다',
    searching: '검색 중...',
    preview: '미리보기',
    weekly: '주간',
    allTime: '전체 기간',
    username: '사용자 이름',
    xpAmount: 'XP 양',
    uploadPhoto: '사진 업로드',
    downloadCard: 'XP 카드 다운로드',
    customizeYourCard: '카드 커스터마이즈',
    enterUsername: '사용자 이름을 입력하세요',
    profilePhoto: '프로필 사진',
    uploadProfilePhoto: '프로필 사진 업로드',
    changePhoto: '사진 변경',
    photoUploaded: '사진이 업로드되었습니다',
    remove: '삭제',
    yourPudgy: '당신의 Pudgy',
    yourLil: '당신의 Lil (Beta)',
    uploadPudgy: 'Pudgy Penguin NFT 업로드',
    uploadLil: 'Lil Pudgy NFT 업로드',
    detectedTraits: '감지된 특성',
    downloadPFP: 'PFP 다운로드',
    comingSoon: '곧 출시',
    big: 'Big',
    lil: 'Lil (Beta)',
    pfpTitle: '프로필 사진 변환기',
    howItWorks: '사용 방법',
    step1Title: 'Pudgy 업로드',
    step1Desc: '기기에서 Pudgy Penguin NFT 이미지를 선택하세요.',
    step2Title: 'AI 감지',
    step2Desc: 'AI가 Pudgy의 특성을 분석하고 감지합니다.',
    step3Title: 'Retsba 받기',
    step3Desc: '고유한 Retsba화된 프로필 사진을 다운로드하세요.',
    yourRetsba: '당신의 Retsba',
    retsbafied: 'Retsbafied',
    dropPudgyHere: 'Pudgy를 여기에 드롭',
    orClickToBrowse: '또는 클릭하여 찾아보기',
    download: '다운로드',
    tryAgain: '다시 시도',
    confidence: '신뢰도',
    heroTagline: '악. 온체인.',
    heroButton: '악당이 되어라',
    aboutTitle: 'RETSBA',
    aboutSubtitle: '어두운 면을 가진 밈코인',
    aboutDescription: '역사상 모든 위대한 전설에는 공통점이 있습니다: 영웅과 악당이 있습니다. 영웅적인 Pudgy Penguins의 세계에서 Retsba는 악당입니다. Anti-Abstract의 깊은 곳에서 온 그는 Abstract 블록체인을 완전히 지배할 때까지 악의 정복을 멈추지 않을 것입니다.',
    buyNowTitle: '지금 구매',
    getOnAbstract: 'Abstract 시작하기',
    getOnAbstractDesc: 'abs.xyz로 이동하세요.',
    fundAccount: '계정 충전',
    fundAccountDesc: '"Fund"를 클릭하여 Abstract ETH를 브릿지하세요.',
    clickTrade: '"Trade" 클릭',
    clickTradeDesc: 'Abstract의 거래 섹션으로 이동하세요.',
    buyRetsba: '$RETSBA 구매',
    buyRetsbaDesc: 'RETSBA 토큰을 검색하고 구매하세요.',
    footerTagline: '악. 온체인.',
    buyRetsbaTitle: 'RETSBA 구매',
    connectWalletToContinue: '계속하려면 지갑을 연결하세요',
    tokenBalance: '토큰 잔액',
    retsbaBalance: 'RETSBA 잔액',
    loading: '로딩 중...',
    amountToCorrupt: '타락시킬 양',
    youWillReceive: '받게 될 금액 (예상)',
    loadingPriceData: '가격 데이터 로딩 중...',
    submitting: '제출 중...',
    loadingPrice: '가격 로딩 중...',
    becomeTheVillain: '악당이 되어라',
    slippageApplied: '슬리피지 적용',
    connectAGW: '연결',
  },
  zh: {
    home: '首页',
    about: '关于',
    giphy: 'Giphy',
    memes: '表情包',
    xpCard: 'XP卡片',
    pfp: 'PFP',
    wallpapers: '壁纸',
    buyNow: '立即购买',
    darkMode: '深色模式',
    language: '语言',
    signIn: '登录',
    signUp: '注册',
    signInSignUp: '登录 / 注册',
    signOut: '退出',
    profile: '个人资料',
    search: '搜索',
    searchProfiles: '搜索用户',
    searchPlaceholder: '按用户名搜索...',
    noResults: '未找到用户',
    searching: '搜索中...',
    preview: '预览',
    weekly: '每周',
    allTime: '全部时间',
    username: '用户名',
    xpAmount: 'XP数量',
    uploadPhoto: '上传照片',
    downloadCard: '下载XP卡片',
    customizeYourCard: '自定义您的卡片',
    enterUsername: '输入您的用户名',
    profilePhoto: '头像',
    uploadProfilePhoto: '上传头像',
    changePhoto: '更换照片',
    photoUploaded: '照片已上传',
    remove: '删除',
    yourPudgy: '你的Pudgy',
    yourLil: '你的Lil (Beta)',
    uploadPudgy: '上传你的Pudgy Penguin NFT',
    uploadLil: '上传你的Lil Pudgy NFT',
    detectedTraits: '检测到的特征',
    downloadPFP: '下载PFP',
    comingSoon: '即将推出',
    big: 'Big',
    lil: 'Lil (Beta)',
    pfpTitle: '头像转换器',
    howItWorks: '使用方法',
    step1Title: '上传你的Pudgy',
    step1Desc: '从设备中选择你的Pudgy Penguin NFT图片。',
    step2Title: 'AI检测',
    step2Desc: '我们的AI分析并检测你的Pudgy特征。',
    step3Title: '获取你的Retsba',
    step3Desc: '下载你独特的Retsba化头像。',
    yourRetsba: '你的Retsba',
    retsbafied: 'Retsbafied',
    dropPudgyHere: '将你的Pudgy拖到这里',
    orClickToBrowse: '或点击浏览',
    download: '下载',
    tryAgain: '重试',
    confidence: '置信度',
    heroTagline: '邪恶。链上。',
    heroButton: '成为恶棍',
    aboutTitle: 'RETSBA',
    aboutSubtitle: '拥有黑暗面的模因币',
    aboutDescription: '历史上每个伟大的传奇都有一个共同点：有英雄，就有恶棍。在英勇的Pudgy Penguins世界中，Retsba就是那个恶棍。他来自Anti-Abstract的深渊，他对邪恶的无情征服不会停止，直到他完全统治Abstract区块链。',
    buyNowTitle: '立即购买',
    getOnAbstract: '进入Abstract',
    getOnAbstractDesc: '访问abs.xyz。',
    fundAccount: '为账户充值',
    fundAccountDesc: '点击"Fund"按钮并桥接Abstract ETH。',
    clickTrade: '点击"Trade"',
    clickTradeDesc: '导航到Abstract的交易部分。',
    buyRetsba: '购买$RETSBA',
    buyRetsbaDesc: '搜索并购买RETSBA代币。',
    footerTagline: '邪恶。链上。',
    buyRetsbaTitle: '购买RETSBA',
    connectWalletToContinue: '请连接钱包以继续',
    tokenBalance: '代币余额',
    retsbaBalance: 'RETSBA余额',
    loading: '加载中...',
    amountToCorrupt: '要腐化的数量',
    youWillReceive: '预计将收到',
    loadingPriceData: '正在加载价格数据...',
    submitting: '提交中...',
    loadingPrice: '加载价格中...',
    becomeTheVillain: '成为恶棍',
    slippageApplied: '滑点已应用',
    connectAGW: '连接',
  },
  fr: {
    home: 'Accueil',
    about: 'À propos',
    giphy: 'Giphy',
    memes: 'Mèmes',
    xpCard: 'Carte XP',
    pfp: 'PFP',
    wallpapers: 'Fonds d\'écran',
    buyNow: 'Acheter',
    darkMode: 'Mode Sombre',
    language: 'Langue',
    signIn: 'Connexion',
    signUp: 'Inscription',
    signInSignUp: 'Connexion / Inscription',
    signOut: 'Déconnexion',
    profile: 'Profil',
    search: 'Rechercher',
    searchProfiles: 'Rechercher des Profils',
    searchPlaceholder: 'Rechercher par nom...',
    noResults: 'Aucun profil trouvé',
    searching: 'Recherche...',
    preview: 'Aperçu',
    weekly: 'Hebdomadaire',
    allTime: 'Tout le Temps',
    username: "Nom d'utilisateur",
    xpAmount: 'Quantité XP',
    uploadPhoto: 'Télécharger Photo',
    downloadCard: 'Télécharger Carte XP',
    customizeYourCard: 'Personnalisez Votre Carte',
    enterUsername: "Entrez votre nom d'utilisateur",
    profilePhoto: 'Photo de Profil',
    uploadProfilePhoto: 'Télécharger Photo de Profil',
    changePhoto: 'Changer Photo',
    photoUploaded: 'Photo téléchargée',
    remove: 'Supprimer',
    yourPudgy: 'Ton Pudgy',
    yourLil: 'Ton Lil (Beta)',
    uploadPudgy: 'Télécharge ton NFT Pudgy Penguin',
    uploadLil: 'Télécharge ton NFT Lil Pudgy',
    detectedTraits: 'Traits Détectés',
    downloadPFP: 'Télécharger PFP',
    comingSoon: 'Bientôt Disponible',
    big: 'Big',
    lil: 'Lil (Beta)',
    pfpTitle: 'Convertisseur de Photo de Profil',
    howItWorks: 'Comment Ça Marche',
    step1Title: 'Télécharge Ton Pudgy',
    step1Desc: 'Sélectionne ton image NFT Pudgy Penguin.',
    step2Title: 'Détection IA',
    step2Desc: "Notre IA analyse et détecte les traits de ton Pudgy.",
    step3Title: 'Obtiens Ton Retsba',
    step3Desc: 'Télécharge ta photo de profil Retsbafied unique.',
    yourRetsba: 'Ton Retsba',
    retsbafied: 'Retsbafied',
    dropPudgyHere: 'Dépose ton Pudgy ici',
    orClickToBrowse: 'ou clique pour parcourir',
    download: 'Télécharger',
    tryAgain: 'Réessayer',
    confidence: 'confiance',
    heroTagline: 'Maléfique. Sur la Chaîne.',
    heroButton: 'SOIS LE MÉCHANT',
    aboutTitle: 'RETSBA',
    aboutSubtitle: 'Le memecoin avec un côté sombre',
    aboutDescription: "Chaque grande légende de l'histoire a eu un point commun : il y a un héros et un méchant. Dans un monde de Pudgy Penguins héroïques, Retsba est le méchant. Venant des profondeurs d'Anti-Abstract, sa conquête implacable du mal ne s'arrêtera pas tant qu'il n'aura pas obtenu la domination totale sur la blockchain Abstract.",
    buyNowTitle: 'ACHETER MAINTENANT',
    getOnAbstract: 'Rejoins Abstract',
    getOnAbstractDesc: 'Va sur abs.xyz.',
    fundAccount: 'Finance ton compte',
    fundAccountDesc: 'Clique sur "Fund" et bridge des Abstract ETH.',
    clickTrade: 'Clique sur "Trade"',
    clickTradeDesc: 'Navigue vers la section trading sur Abstract.',
    buyRetsba: 'Achète $RETSBA',
    buyRetsbaDesc: 'Recherche et achète des tokens RETSBA.',
    footerTagline: 'Maléfique. Sur la chaîne.',
    buyRetsbaTitle: 'Acheter RETSBA',
    connectWalletToContinue: 'Veuillez connecter votre portefeuille pour continuer',
    tokenBalance: 'Solde du Token',
    retsbaBalance: 'Solde RETSBA',
    loading: 'Chargement...',
    amountToCorrupt: 'Montant à corrompre',
    youWillReceive: 'Vous recevrez (estimé)',
    loadingPriceData: 'Chargement des données de prix...',
    submitting: 'Envoi en cours...',
    loadingPrice: 'Chargement du Prix...',
    becomeTheVillain: 'Deviens le Méchant',
    slippageApplied: 'glissement appliqué',
    connectAGW: 'Connecter',
  },
  de: {
    home: 'Startseite',
    about: 'Über uns',
    giphy: 'Giphy',
    memes: 'Memes',
    xpCard: 'XP-Karte',
    pfp: 'PFP',
    wallpapers: 'Hintergrundbilder',
    buyNow: 'Jetzt Kaufen',
    darkMode: 'Dunkelmodus',
    language: 'Sprache',
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    signInSignUp: 'Anmelden / Registrieren',
    signOut: 'Abmelden',
    profile: 'Profil',
    search: 'Suchen',
    searchProfiles: 'Profile Suchen',
    searchPlaceholder: 'Nach Benutzername suchen...',
    noResults: 'Keine Profile gefunden',
    searching: 'Suche...',
    preview: 'Vorschau',
    weekly: 'Wöchentlich',
    allTime: 'Gesamtzeit',
    username: 'Benutzername',
    xpAmount: 'XP-Menge',
    uploadPhoto: 'Foto Hochladen',
    downloadCard: 'XP-Karte Herunterladen',
    customizeYourCard: 'Karte Anpassen',
    enterUsername: 'Benutzername eingeben',
    profilePhoto: 'Profilfoto',
    uploadProfilePhoto: 'Profilfoto Hochladen',
    changePhoto: 'Foto Ändern',
    photoUploaded: 'Foto hochgeladen',
    remove: 'Entfernen',
    yourPudgy: 'Dein Pudgy',
    yourLil: 'Dein Lil (Beta)',
    uploadPudgy: 'Lade dein Pudgy Penguin NFT hoch',
    uploadLil: 'Lade dein Lil Pudgy NFT hoch',
    detectedTraits: 'Erkannte Merkmale',
    downloadPFP: 'PFP Herunterladen',
    comingSoon: 'Demnächst',
    big: 'Big',
    lil: 'Lil (Beta)',
    pfpTitle: 'Profilbild-Konverter',
    howItWorks: 'So Funktioniert Es',
    step1Title: 'Lade Deinen Pudgy Hoch',
    step1Desc: 'Wähle dein Pudgy Penguin NFT-Bild aus.',
    step2Title: 'KI-Erkennung',
    step2Desc: 'Unsere KI analysiert und erkennt die Eigenschaften deines Pudgy.',
    step3Title: 'Hol Dir Deinen Retsba',
    step3Desc: 'Lade dein einzigartiges Retsba-Profilbild herunter.',
    yourRetsba: 'Dein Retsba',
    retsbafied: 'Retsbafied',
    dropPudgyHere: 'Pudgy hier ablegen',
    orClickToBrowse: 'oder klicken zum Durchsuchen',
    download: 'Herunterladen',
    tryAgain: 'Erneut Versuchen',
    confidence: 'Vertrauen',
    heroTagline: 'Böse. Auf der Chain.',
    heroButton: 'SEI DER BÖSEWICHT',
    aboutTitle: 'RETSBA',
    aboutSubtitle: 'Die Memecoin mit einer dunklen Seite',
    aboutDescription: 'Jede große Legende der Geschichte hatte eine Gemeinsamkeit: Es gibt einen Helden und einen Bösewicht. In einer Welt heroischer Pudgy Penguins ist Retsba der Bösewicht. Aus den Tiefen von Anti-Abstract kommend, wird seine unerbittliche Eroberung des Bösen nicht enden, bis er die totale Herrschaft über die Abstract-Blockchain erlangt hat.',
    buyNowTitle: 'JETZT KAUFEN',
    getOnAbstract: 'Auf Abstract einsteigen',
    getOnAbstractDesc: 'Gehe zu abs.xyz.',
    fundAccount: 'Konto aufladen',
    fundAccountDesc: 'Klicke auf "Fund" und bridge Abstract ETH.',
    clickTrade: 'Klicke auf "Trade"',
    clickTradeDesc: 'Navigiere zum Trading-Bereich auf Abstract.',
    buyRetsba: 'Kaufe $RETSBA',
    buyRetsbaDesc: 'Suche und kaufe RETSBA-Token.',
    footerTagline: 'Böse. Auf der Chain.',
    buyRetsbaTitle: 'RETSBA Kaufen',
    connectWalletToContinue: 'Bitte verbinde dein Wallet um fortzufahren',
    tokenBalance: 'Token-Guthaben',
    retsbaBalance: 'RETSBA-Guthaben',
    loading: 'Laden...',
    amountToCorrupt: 'Menge zum Korrumpieren',
    youWillReceive: 'Du erhältst (geschätzt)',
    loadingPriceData: 'Lade Preisdaten...',
    submitting: 'Wird gesendet...',
    loadingPrice: 'Lade Preis...',
    becomeTheVillain: 'Werde der Bösewicht',
    slippageApplied: 'Slippage angewendet',
    connectAGW: 'Verbinden',
  },
  pt: {
    home: 'Início',
    about: 'Sobre',
    giphy: 'Giphy',
    memes: 'Memes',
    xpCard: 'Cartão XP',
    pfp: 'PFP',
    wallpapers: 'Papéis de Parede',
    buyNow: 'Comprar Agora',
    darkMode: 'Modo Escuro',
    language: 'Idioma',
    signIn: 'Entrar',
    signUp: 'Cadastrar',
    signInSignUp: 'Entrar / Cadastrar',
    signOut: 'Sair',
    profile: 'Perfil',
    search: 'Buscar',
    searchProfiles: 'Buscar Perfis',
    searchPlaceholder: 'Buscar por nome de usuário...',
    noResults: 'Nenhum perfil encontrado',
    searching: 'Buscando...',
    preview: 'Prévia',
    weekly: 'Semanal',
    allTime: 'Todo o Tempo',
    username: 'Nome de Usuário',
    xpAmount: 'Quantidade de XP',
    uploadPhoto: 'Enviar Foto',
    downloadCard: 'Baixar Cartão XP',
    customizeYourCard: 'Personalize Seu Cartão',
    enterUsername: 'Digite seu nome de usuário',
    profilePhoto: 'Foto de Perfil',
    uploadProfilePhoto: 'Enviar Foto de Perfil',
    changePhoto: 'Trocar Foto',
    photoUploaded: 'Foto enviada',
    remove: 'Remover',
    yourPudgy: 'Seu Pudgy',
    yourLil: 'Seu Lil (Beta)',
    uploadPudgy: 'Envie seu NFT Pudgy Penguin',
    uploadLil: 'Envie seu NFT Lil Pudgy',
    detectedTraits: 'Características Detectadas',
    downloadPFP: 'Baixar PFP',
    comingSoon: 'Em Breve',
    big: 'Big',
    lil: 'Lil (Beta)',
    pfpTitle: 'Conversor de Foto de Perfil',
    howItWorks: 'Como Funciona',
    step1Title: 'Envie Seu Pudgy',
    step1Desc: 'Selecione sua imagem NFT Pudgy Penguin.',
    step2Title: 'Detecção por IA',
    step2Desc: 'Nossa IA analisa e detecta as características do seu Pudgy.',
    step3Title: 'Obtenha Seu Retsba',
    step3Desc: 'Baixe sua foto de perfil Retsbafied única.',
    yourRetsba: 'Seu Retsba',
    retsbafied: 'Retsbafied',
    dropPudgyHere: 'Solte seu Pudgy aqui',
    orClickToBrowse: 'ou clique para navegar',
    download: 'Baixar',
    tryAgain: 'Tentar Novamente',
    confidence: 'confiança',
    heroTagline: 'Malvado. Na Blockchain.',
    heroButton: 'SEJA O VILÃO',
    aboutTitle: 'RETSBA',
    aboutSubtitle: 'A memecoin com um lado sombrio',
    aboutDescription: 'Toda grande lenda da história teve algo em comum: há um herói e um vilão. Em um mundo de Pudgy Penguins heróicos, Retsba é o vilão. Vindo das profundezas do Anti-Abstract, sua conquista implacável do mal não terminará até que ele obtenha o domínio total sobre a blockchain Abstract.',
    buyNowTitle: 'COMPRAR AGORA',
    getOnAbstract: 'Entre no Abstract',
    getOnAbstractDesc: 'Acesse abs.xyz.',
    fundAccount: 'Financie sua conta',
    fundAccountDesc: 'Clique em "Fund" e faça bridge de Abstract ETH.',
    clickTrade: 'Clique em "Trade"',
    clickTradeDesc: 'Navegue até a seção de trading no Abstract.',
    buyRetsba: 'Compre $RETSBA',
    buyRetsbaDesc: 'Pesquise e compre tokens RETSBA.',
    footerTagline: 'Malvado. Na blockchain.',
    buyRetsbaTitle: 'Comprar RETSBA',
    connectWalletToContinue: 'Por favor conecte sua carteira para continuar',
    tokenBalance: 'Saldo do Token',
    retsbaBalance: 'Saldo RETSBA',
    loading: 'Carregando...',
    amountToCorrupt: 'Quantidade para corromper',
    youWillReceive: 'Você receberá (estimado)',
    loadingPriceData: 'Carregando dados de preço...',
    submitting: 'Enviando...',
    loadingPrice: 'Carregando Preço...',
    becomeTheVillain: 'Seja o Vilão',
    slippageApplied: 'deslizamento aplicado',
    connectAGW: 'Conectar',
  },
  ru: {
    home: 'Главная',
    about: 'О нас',
    giphy: 'Giphy',
    memes: 'Мемы',
    xpCard: 'XP Карта',
    pfp: 'PFP',
    wallpapers: 'Обои',
    buyNow: 'Купить',
    darkMode: 'Тёмный Режим',
    language: 'Язык',
    signIn: 'Войти',
    signUp: 'Регистрация',
    signInSignUp: 'Войти / Регистрация',
    signOut: 'Выйти',
    profile: 'Профиль',
    search: 'Поиск',
    searchProfiles: 'Поиск Профилей',
    searchPlaceholder: 'Поиск по имени...',
    noResults: 'Профили не найдены',
    searching: 'Поиск...',
    preview: 'Предпросмотр',
    weekly: 'Еженедельно',
    allTime: 'Всё Время',
    username: 'Имя пользователя',
    xpAmount: 'Количество XP',
    uploadPhoto: 'Загрузить Фото',
    downloadCard: 'Скачать XP Карту',
    customizeYourCard: 'Настройте Вашу Карту',
    enterUsername: 'Введите имя пользователя',
    profilePhoto: 'Фото Профиля',
    uploadProfilePhoto: 'Загрузить Фото Профиля',
    changePhoto: 'Изменить Фото',
    photoUploaded: 'Фото загружено',
    remove: 'Удалить',
    yourPudgy: 'Ваш Pudgy',
    yourLil: 'Ваш Lil (Beta)',
    uploadPudgy: 'Загрузите ваш Pudgy Penguin NFT',
    uploadLil: 'Загрузите ваш Lil Pudgy NFT',
    detectedTraits: 'Обнаруженные Черты',
    downloadPFP: 'Скачать PFP',
    comingSoon: 'Скоро',
    big: 'Big',
    lil: 'Lil (Beta)',
    pfpTitle: 'Конвертер Фото Профиля',
    howItWorks: 'Как Это Работает',
    step1Title: 'Загрузите Вашего Pudgy',
    step1Desc: 'Выберите изображение NFT Pudgy Penguin.',
    step2Title: 'ИИ Обнаружение',
    step2Desc: 'Наш ИИ анализирует и определяет черты вашего Pudgy.',
    step3Title: 'Получите Вашего Retsba',
    step3Desc: 'Скачайте уникальную Retsba-фото профиля.',
    yourRetsba: 'Ваш Retsba',
    retsbafied: 'Retsbafied',
    dropPudgyHere: 'Перетащите Pudgy сюда',
    orClickToBrowse: 'или нажмите для выбора',
    download: 'Скачать',
    tryAgain: 'Попробовать Снова',
    confidence: 'уверенность',
    heroTagline: 'Зло. В Сети.',
    heroButton: 'СТАНЬ ЗЛОДЕЕМ',
    aboutTitle: 'RETSBA',
    aboutSubtitle: 'Мемкоин с тёмной стороной',
    aboutDescription: 'Каждая великая легенда в истории имела одну общую черту: есть герой и злодей. В мире героических Pudgy Penguins, Retsba — злодей. Пришедший из глубин Anti-Abstract, его безжалостное завоевание зла не закончится, пока он не получит полное господство над блокчейном Abstract.',
    buyNowTitle: 'КУПИТЬ СЕЙЧАС',
    getOnAbstract: 'Присоединяйтесь к Abstract',
    getOnAbstractDesc: 'Перейдите на abs.xyz.',
    fundAccount: 'Пополните счёт',
    fundAccountDesc: 'Нажмите "Fund" и переведите Abstract ETH.',
    clickTrade: 'Нажмите "Trade"',
    clickTradeDesc: 'Перейдите в раздел торговли на Abstract.',
    buyRetsba: 'Купите $RETSBA',
    buyRetsbaDesc: 'Найдите и купите токены RETSBA.',
    footerTagline: 'Зло. В сети.',
    buyRetsbaTitle: 'Купить RETSBA',
    connectWalletToContinue: 'Пожалуйста, подключите кошелёк для продолжения',
    tokenBalance: 'Баланс Токена',
    retsbaBalance: 'Баланс RETSBA',
    loading: 'Загрузка...',
    amountToCorrupt: 'Сумма для коррупции',
    youWillReceive: 'Вы получите (приблизительно)',
    loadingPriceData: 'Загрузка данных о цене...',
    submitting: 'Отправка...',
    loadingPrice: 'Загрузка Цены...',
    becomeTheVillain: 'Стань Злодеем',
    slippageApplied: 'применено проскальзывание',
    connectAGW: 'Подключить',
  },
  ar: {
    home: 'الرئيسية',
    about: 'حول',
    giphy: 'Giphy',
    memes: 'ميمز',
    xpCard: 'بطاقة XP',
    pfp: 'PFP',
    wallpapers: 'خلفيات',
    buyNow: 'اشتري الآن',
    darkMode: 'الوضع الداكن',
    language: 'اللغة',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    signInSignUp: 'دخول / تسجيل',
    signOut: 'تسجيل الخروج',
    profile: 'الملف الشخصي',
    search: 'بحث',
    searchProfiles: 'البحث عن مستخدمين',
    searchPlaceholder: 'البحث باسم المستخدم...',
    noResults: 'لم يتم العثور على مستخدمين',
    searching: 'جاري البحث...',
    preview: 'معاينة',
    weekly: 'أسبوعي',
    allTime: 'كل الأوقات',
    username: 'اسم المستخدم',
    xpAmount: 'كمية XP',
    uploadPhoto: 'رفع صورة',
    downloadCard: 'تحميل بطاقة XP',
    customizeYourCard: 'خصص بطاقتك',
    enterUsername: 'أدخل اسم المستخدم',
    profilePhoto: 'صورة الملف الشخصي',
    uploadProfilePhoto: 'رفع صورة الملف الشخصي',
    changePhoto: 'تغيير الصورة',
    photoUploaded: 'تم رفع الصورة',
    remove: 'إزالة',
    yourPudgy: 'Pudgy الخاص بك',
    yourLil: 'Lil الخاص بك (Beta)',
    uploadPudgy: 'ارفع NFT الخاص بـ Pudgy Penguin',
    uploadLil: 'ارفع NFT الخاص بـ Lil Pudgy',
    detectedTraits: 'السمات المكتشفة',
    downloadPFP: 'تحميل PFP',
    comingSoon: 'قريباً',
    big: 'Big',
    lil: 'Lil (Beta)',
    pfpTitle: 'محول صورة الملف الشخصي',
    howItWorks: 'كيف يعمل',
    step1Title: 'ارفع Pudgy الخاص بك',
    step1Desc: 'اختر صورة NFT Pudgy Penguin من جهازك.',
    step2Title: 'اكتشاف الذكاء الاصطناعي',
    step2Desc: 'يقوم الذكاء الاصطناعي بتحليل واكتشاف سمات Pudgy.',
    step3Title: 'احصل على Retsba الخاص بك',
    step3Desc: 'قم بتنزيل صورة ملفك الشخصي Retsba الفريدة.',
    yourRetsba: 'Retsba الخاص بك',
    retsbafied: 'Retsbafied',
    dropPudgyHere: 'أسقط Pudgy هنا',
    orClickToBrowse: 'أو انقر للتصفح',
    download: 'تحميل',
    tryAgain: 'حاول مرة أخرى',
    confidence: 'ثقة',
    heroTagline: 'شر. على السلسلة.',
    heroButton: 'كن الشرير',
    aboutTitle: 'RETSBA',
    aboutSubtitle: 'عملة الميم ذات الجانب المظلم',
    aboutDescription: 'كل أسطورة عظيمة في التاريخ كان لها قاسم مشترك: هناك بطل وهناك شرير. في عالم Pudgy Penguins البطولي، Retsba هو الشرير. قادم من أعماق Anti-Abstract، لن ينتهي غزوه الذي لا يرحم للشر حتى يحصل على السيطرة الكاملة على بلوكتشين Abstract.',
    buyNowTitle: 'اشتري الآن',
    getOnAbstract: 'انضم إلى Abstract',
    getOnAbstractDesc: 'اذهب إلى abs.xyz.',
    fundAccount: 'موّل حسابك',
    fundAccountDesc: 'انقر على "Fund" وقم بتحويل Abstract ETH.',
    clickTrade: 'انقر على "Trade"',
    clickTradeDesc: 'انتقل إلى قسم التداول في Abstract.',
    buyRetsba: 'اشتري $RETSBA',
    buyRetsbaDesc: 'ابحث عن واشتري رموز RETSBA.',
    footerTagline: 'شر. على السلسلة.',
    buyRetsbaTitle: 'شراء RETSBA',
    connectWalletToContinue: 'يرجى توصيل محفظتك للمتابعة',
    tokenBalance: 'رصيد التوكن',
    retsbaBalance: 'رصيد RETSBA',
    loading: 'جاري التحميل...',
    amountToCorrupt: 'المبلغ للإفساد',
    youWillReceive: 'ستحصل على (تقديري)',
    loadingPriceData: 'جاري تحميل بيانات السعر...',
    submitting: 'جاري الإرسال...',
    loadingPrice: 'جاري تحميل السعر...',
    becomeTheVillain: 'كن الشرير',
    slippageApplied: 'الانزلاق مطبق',
    connectAGW: 'اتصال',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  t: (key: TranslationKey) => string;
  currentLanguage: Language;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Detect browser language and map to supported language
const detectBrowserLanguage = (): LanguageCode => {
  const browserLang = navigator.language || (navigator as any).userLanguage || 'en';
  const langCode = browserLang.split('-')[0].toLowerCase(); // e.g., 'en-US' -> 'en'
  
  // Check if the detected language is in our supported list
  const supportedCodes: LanguageCode[] = ['en', 'es', 'ja', 'ko', 'zh', 'fr', 'de', 'pt', 'ru', 'ar'];
  if (supportedCodes.includes(langCode as LanguageCode)) {
    return langCode as LanguageCode;
  }
  
  return 'en'; // Default to English if not supported
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('language');
    if (saved && ['en', 'es', 'ja', 'ko', 'zh', 'fr', 'de', 'pt', 'ru', 'ar'].includes(saved)) {
      return saved as LanguageCode;
    }
    // No saved preference, detect from browser
    return detectBrowserLanguage();
  });

  const setLanguage = (code: LanguageCode) => {
    setLanguageState(code);
    localStorage.setItem('language', code);
  };

  const t = (key: TranslationKey): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  const currentLanguage = LANGUAGES.find(l => l.code === language) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
